import 'package:flutter/material.dart';

// ─── Enums ────────────────────────────────────────────────────────────────

enum Difficulty { easy, medium, hard, extreme }

// ─── Local UI Habit (simplified, not the API model) ──────────────────────

/// Lightweight UI model for rendering habit cards.
/// Populated by converting [api.Habit] in the provider layer.
class Habit {
  final String id;
  final String name;
  final String category;
  final int xp;
  bool completed;
  bool isBad;
  int streakCount;

  Habit({
    required this.id,
    required this.name,
    required this.category,
    required this.xp,
    this.completed = false,
    this.isBad = false,
    this.streakCount = 0,
  });
}

// ─── App Challenge ─────────────────────────────────────────────────────────

class AppChallenge {
  final String id;
  final String title;
  final String description;
  final int xp;
  final int progress;
  final int target;
  final bool completed;

  const AppChallenge({
    required this.id,
    required this.title,
    required this.description,
    required this.xp,
    required this.progress,
    required this.target,
    this.completed = false,
  });

  AppChallenge copyWith({
    String? id,
    String? title,
    String? description,
    int? xp,
    int? progress,
    int? target,
    bool? completed,
  }) {
    return AppChallenge(
      id: id ?? this.id,
      title: title ?? this.title,
      description: description ?? this.description,
      xp: xp ?? this.xp,
      progress: progress ?? this.progress,
      target: target ?? this.target,
      completed: completed ?? this.completed,
    );
  }
}

// ─── Recommendation ────────────────────────────────────────────────────────

/// A recommended habit to try, generated by the rules engine.
class Recommendation {
  final String id;
  final String name;
  final String description;
  final String category;
  final String difficulty; // "Easy", "Medium", "Hard", "Extreme"
  final String reason; // Explanation why this is recommended
  final IconData icon;

  const Recommendation({
    required this.id,
    required this.name,
    required this.description,
    required this.category,
    required this.difficulty,
    required this.reason,
    this.icon = Icons.lightbulb_outline,
  });
}

// ─── Player Stat (RPG) ────────────────────────────────────────────────────

/// An RPG-style stat that levels up from completing habits.
class PlayerStat {
  final String id;
  String name;
  double value;
  int level;
  int xpInStat;
  int xpToNext;
  String icon;
  String color;
  String categoryMappings; // JSON array of category strings

  PlayerStat({
    required this.id,
    required this.name,
    required this.value,
    required this.level,
    required this.xpInStat,
    required this.xpToNext,
    required this.icon,
    required this.color,
    required this.categoryMappings,
  });

  factory PlayerStat.fromJson(Map<String, dynamic> json) {
    return PlayerStat(
      id: json['id'] as String,
      name: json['name'] as String,
      value: (json['value'] as num).toDouble(),
      level: json['level'] as int,
      xpInStat: json['xp_in_stat'] as int,
      xpToNext: json['xp_to_next'] as int,
      icon: json['icon'] as String,
      color: json['color'] as String,
      categoryMappings: json['category_mappings'] as String,
    );
  }

  Map<String, dynamic> toJson() => {
    'id': id,
    'name': name,
    'value': value,
    'level': level,
    'xp_in_stat': xpInStat,
    'xp_to_next': xpToNext,
    'icon': icon,
    'color': color,
    'category_mappings': categoryMappings,
  };

  double get progress => xpToNext > 0 ? (xpInStat / xpToNext).clamp(0.0, 1.0) : 0.0;

  Color get displayColor {
    try {
      return Color(int.parse(color.replaceFirst('#', '0xFF')));
    } catch (_) {
      return const Color(0xFFFF9B71);
    }
  }

  List<String> get mappedCategories {
    try {
      final list = categoryMappings as List<dynamic>?;
      if (list != null) return list.cast<String>();
      return [];
    } catch (_) {
      return [];
    }
  }
}

// ─── App Data (global state) ──────────────────────────────────────────────

class AppData {
  final List<Habit> habits;
  final List<AppChallenge> challenges;
  final int level;
  final int currentXP;
  final int neededXP;
  final List<Recommendation> recommendations;
  final List<PlayerStat> stats;
  final bool isLoading;

  const AppData({
    required this.habits,
    required this.challenges,
    required this.level,
    required this.currentXP,
    required this.neededXP,
    required this.recommendations,
    this.stats = const [],
    this.isLoading = false,
  });

  factory AppData.initial() => AppData(
        habits: [],
        challenges: const <AppChallenge>[],
        level: 1,
        currentXP: 0,
        neededXP: 100,
        recommendations: const <Recommendation>[],
        stats: [],
      );

  factory AppData.empty() => AppData(
        habits: [],
        challenges: const <AppChallenge>[],
        level: 0,
        currentXP: 0,
        neededXP: 0,
        recommendations: const <Recommendation>[],
        stats: const [],
      );

  AppData copyWith({
    List<Habit>? habits,
    List<AppChallenge>? challenges,
    int? level,
    int? currentXP,
    int? neededXP,
    List<Recommendation>? recommendations,
    List<PlayerStat>? stats,
    bool? isLoading,
  }) =>
      AppData(
        habits: habits ?? List.from(this.habits),
        challenges: challenges ?? this.challenges,
        level: level ?? this.level,
        currentXP: currentXP ?? this.currentXP,
        neededXP: neededXP ?? this.neededXP,
        recommendations: recommendations ?? List.from(this.recommendations),
        stats: stats ?? this.stats,
        isLoading: isLoading ?? this.isLoading,
      );

  int get completedToday => habits.where((h) => h.completed).length;

  static int xpForDifficulty(String diff) {
    return switch (diff) {
      'Easy' => 10,
      'Medium' => 25,
      'Hard' => 50,
      'Extreme' => 100,
      _ => 10,
    };
  }
}